### ISSUE TITLE
How do we rebuild the architectures in the benchmark?

### ISSUE THREAD

**Issue by tamdan17** [THUMNLab/NAS-Bench-Graph#1]
Can you send me the source code to rebuild the architectures and train them in the benchmark?

**Comment by general502570** [comment]
We provide the benchmark generation code in the supplementary files of the paper. Please download at
https://openreview.net/forum?id=bBff294gqLp&referrer=%5BAuthor%20Console%5D(%2Fgroup%3Fid%3DNeurIPS.cc%2F2022%2FTrack%2FDatasets_and_Benchmarks%2FAuthors%23your-submissions)
